name: Test bun_server (prettier, eslint, bdd)

on:
  # push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Setup actions
      uses: actions/checkout@v4
    - name: Setup bun
      uses: oven-sh/setup-bun@v1
    - name: Run prettier
      run: |-
        cd bun_server
        bun i
        bun run pretty
  lint:
    needs: prettier
    runs-on: ubuntu-latest
    steps:
    - name: Setup actions
      uses: actions/checkout@v4
    - name: Setup bun
      uses: oven-sh/setup-bun@v1
    - name: Run lint
      run: |-
        cd bun_server
        bun i
        bun run lint

  bdd:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup actions
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Run bdd
        run: |-
          cd bun_server
          bun i
          bun start &
          cd ../bdd
          bun i
          bun cypress install
          bun cypress run

