name: Test check

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Setup actions
      uses: actions/checkout@v3
    - name: Setup bun
      uses: oven-sh/setup-bun@v1
    - name: Run prettier
      run: |-
        cd bun_server
        bun install
        bun prettier . --check