name: Test bun_server (prettier, eslint)

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Setup actions
      uses: actions/checkout@v3
    - name: Setup bun
      uses: oven-sh/setup-bun@v1
    - name: Run prettier
      run: |-
        cd bun_server
        bun i
        bun run pretty
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup actions
      uses: actions/checkout@v3
    - name: Setup bun
      uses: oven-sh/setup-bun@v1
    - name: Run lint
      run: |-
        cd bun_server
        bun i
        bun run lint